# Generated by Django 6.0.7 on 2026-07-29 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamesession',
            name='event_name',
            field=models.CharField(default='standard', max_length=255),
        ),
    ]
