# Generated by Django 6.0.7 on 2026-07-29 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_gamesession_event_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playerresult',
            name='grade_level',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='playerresult',
            name='school_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
