# Generated by Django 6.0.7 on 2026-07-30 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0003_alter_playerresult_grade_level_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bid2BuildTeam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(db_index=True, max_length=10, unique=True)),
                ('assigned_name', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
