# Generated by Django 6.0.7 on 2026-08-01 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0004_bid2buildteam'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Bid2BuildTeam',
        ),
        migrations.AddField(
            model_name='playerresult',
            name='team_code',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
