# Generated by Django 6.0.7 on 2026-08-11 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0005_delete_bid2buildteam_playerresult_team_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='media_type',
            field=models.CharField(blank=True, choices=[('image', 'Image'), ('video', 'Video'), ('audio', 'Audio')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='media_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
