# Generated by Django 6.0.7 on 2026-08-18 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0006_question_media_type_question_media_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='playerresult',
            name='contact_info',
        ),
        migrations.RemoveField(
            model_name='playerresult',
            name='full_name',
        ),
        migrations.RemoveField(
            model_name='playerresult',
            name='grade_level',
        ),
        migrations.RemoveField(
            model_name='playerresult',
            name='player_id',
        ),
        migrations.RemoveField(
            model_name='playerresult',
            name='school_name',
        ),
        migrations.AddField(
            model_name='playerresult',
            name='correct_answers',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='playerresult',
            name='name',
            field=models.CharField(default='name', max_length=255),
        ),
        migrations.AddField(
            model_name='playerresult',
            name='total_time',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='quiz',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='gamesession',
            name='event_name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='playerresult',
            name='team_code',
            field=models.CharField(db_index=True, default='AAAA', max_length=10),
        ),
        migrations.AddConstraint(
            model_name='playerresult',
            constraint=models.UniqueConstraint(fields=('session', 'team_code'), name='unique_team_per_session'),
        ),
    ]
