# Generated by Django 6.0.7 on 2026-08-18 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0007_remove_playerresult_contact_info_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playerresult',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='playerresult',
            name='team_code',
            field=models.CharField(db_index=True, max_length=10),
        ),
    ]
